### Mathematical functions and operators
PostgreSQL supports all standard mathematical functions and operators in it's standard library. 

Below is an example of using mathematical operators (such as division and multiplication) and mathematical functions (**`ROUND`**), along with previously unseen aggregate function that returns an array.

For full information, visit the documentation:
* https://www.postgresql.org/docs/current/functions-math.html
* https://www.postgresql.org/docs/current/functions-aggregate.html#FUNCTIONS-AGGREGATE-TABLE

*__Task__*: Calculate movie titles' rental cost as a percentage of their replacement cost.

In [1]:
from utils.query_db import db_connection
import pandas as pd

with (db_connection() as conn,
      pd.option_context("display.max_rows", None,
                        "display.max_colwidth", None)):
    
    conn.fetch_all("""
        SELECT COUNT(film_id),
               ROUND(rental_rate / replacement_cost * 100, 2)
                    AS replacement_percentage_cost,
               array_agg(film_id) as film_ids
        FROM film
        GROUP BY replacement_percentage_cost
        ORDER BY replacement_percentage_cost;
    """)

,count,replacement_percentage_cost,film_ids
0,22,3.30,"[34, 52, 85, 157, 163, 196, 270, 290, 309, 358, 366, 374, 417, 423, 429, 475, 525, 663, 733, 762, 819, 901]"
1,15,3.41,"[245, 344, 395, 517, 549, 730, 737, 741, 794, 849, 855, 866, 909, 951, 965]"
2,21,3.54,"[18, 66, 191, 200, 266, 303, 387, 418, 586, 650, 738, 743, 752, 816, 850, 852, 868, 906, 925, 942, 949]"
3,16,3.67,"[64, 101, 114, 118, 155, 249, 250, 280, 404, 458, 509, 722, 728, 799, 834, 840]"
4,18,3.81,"[38, 110, 132, 178, 204, 206, 317, 434, 504, 555, 585, 622, 677, 742, 750, 766, 807, 862]"
5,9,3.96,"[97, 130, 142, 301, 360, 617, 718, 882, 974]"
6,18,4.13,"[14, 76, 140, 168, 189, 335, 430, 488, 511, 717, 744, 795, 797, 830, 839, 877, 894, 982]"
7,16,4.31,"[12, 40, 89, 119, 194, 205, 218, 269, 352, 406, 594, 598, 790, 885, 945, 948]"
8,17,4.50,"[63, 105, 149, 176, 382, 440, 457, 494, 523, 560, 535, 618, 641, 736, 810, 864, 932]"
9,24,4.72,"[1, 19, 164, 241, 282, 292, 367, 376, 377, 425, 454, 753, 566, 589, 595, 599, 601, 619, 651, 681, 696, 831, 833, 913]"
10,16,4.95,"[213, 108, 225, 247, 287, 427, 538, 547, 574, 613, 630, 673, 848, 851, 910, 940]"
11,11,5.21,"[153, 285, 355, 491, 493, 516, 531, 534, 625, 647, 813]"
12,16,5.50,"[41, 91, 109, 111, 143, 186, 233, 262, 339, 345, 610, 732, 751, 821, 935, 992]"
13,12,5.83,"[11, 147, 228, 332, 388, 581, 600, 697, 748, 832, 920, 947]"
14,11,6.19,"[26, 54, 402, 452, 477, 497, 552, 606, 635, 687, 924]"
15,21,6.60,"[17, 87, 257, 273, 295, 311, 318, 379, 436, 461, 489, 545, 602, 634, 652, 786, 809, 890, 899, 966, 997]"
16,15,7.08,"[82, 242, 261, 314, 341, 357, 383, 507, 524, 593, 812, 891, 873, 981, 990]"
17,22,7.62,"[27, 36, 160, 306, 363, 407, 424, 479, 482, 553, 562, 636, 646, 688, 727, 787, 796, 822, 870, 963, 976, 978]"
18,9,8.26,"[90, 122, 258, 275, 492, 631, 674, 712, 970]"
19,17,9.01,"[39, 79, 128, 283, 291, 315, 401, 416, 467, 496, 577, 604, 746, 808, 896, 907, 998]"
20,15,9.91,"[23, 221, 281, 299, 348, 623, 629, 656, 747, 863, 875, 886, 931, 953, 996]"
21,21,9.97,"[138, 199, 232, 238, 297, 302, 322, 325, 450, 480, 483, 537, 644, 698, 707, 714, 723, 726, 759, 811, 921]"
22,11,10.31,"[37, 304, 328, 447, 520, 542, 592, 729, 757, 773, 999]"
23,15,10.68,"[30, 55, 115, 175, 180, 197, 231, 234, 349, 519, 530, 546, 548, 557, 872]"
24,14,11.08,"[4, 136, 370, 397, 561, 567, 571, 584, 716, 735, 782, 967, 988, 991]"
25,10,11.50,"[53, 331, 361, 391, 448, 528, 690, 704, 806, 977]"
26,17,11.96,"[35, 67, 146, 184, 188, 209, 223, 305, 378, 442, 503, 505, 628, 772, 857, 917, 986]"
27,15,12.46,"[16, 62, 296, 399, 414, 415, 433, 471, 609, 620, 621, 638, 678, 761, 930]"
28,21,13.01,"[5, 49, 73, 135, 198, 319, 353, 432, 438, 481, 550, 554, 559, 573, 643, 665, 774, 783, 825, 869, 975]"
29,21,13.60,"[9, 69, 80, 96, 137, 237, 394, 428, 441, 463, 474, 502, 513, 533, 539, 541, 615, 760, 823, 895, 936]"
30,11,14.24,"[50, 59, 193, 230, 274, 288, 368, 667, 720, 784, 984]"
31,15,14.96,"[24, 125, 166, 169, 236, 393, 410, 419, 582, 616, 658, 709, 800, 837, 958]"
32,12,15.75,"[3, 57, 83, 201, 252, 326, 536, 558, 569, 645, 962, 983]"
33,15,16.62,"[6, 104, 293, 375, 453, 462, 514, 590, 672, 675, 679, 754, 900, 939, 952]"
34,10,16.64,"[81, 224, 487, 510, 691, 731, 803, 944, 969, 994]"
35,15,17.21,"[7, 265, 61, 170, 276, 320, 342, 408, 435, 439, 521, 532, 764, 887, 889]"
36,11,17.60,"[58, 129, 158, 208, 286, 333, 413, 473, 693, 927, 928]"
37,17,17.83,"[93, 103, 161, 165, 215, 222, 268, 420, 469, 575, 603, 666, 671, 817, 897, 943, 973]"
38,16,18.49,"[68, 70, 151, 202, 207, 244, 294, 372, 385, 460, 556, 583, 699, 763, 904, 957]"
39,14,18.70,"[25, 33, 43, 56, 121, 259, 329, 400, 724, 788, 789, 792, 802, 960]"
40,15,19.20,"[71, 145, 173, 289, 381, 412, 422, 512, 596, 624, 668, 715, 725, 838, 878]"
41,12,19.95,"[94, 99, 106, 343, 364, 373, 649, 689, 793, 815, 836, 937]"
42,12,19.97,"[10, 48, 144, 277, 327, 470, 472, 499, 527, 778, 791, 972]"
43,12,20.80,"[20, 47, 190, 284, 338, 459, 721, 745, 771, 779, 918, 956]"
44,25,21.37,"[107, 148, 152, 162, 220, 235, 264, 298, 308, 362, 437, 464, 484, 490, 576, 605, 642, 700, 740, 770, 835, 842, 874, 914, 987]"
45,18,21.71,"[60, 112, 123, 243, 323, 330, 336, 369, 444, 579, 655, 706, 827, 854, 902, 922, 961, 989]"
46,17,22.69,"[13, 44, 100, 134, 139, 255, 300, 321, 334, 350, 365, 398, 640, 680, 769, 858, 929]"
47,15,23.02,"[72, 78, 154, 187, 449, 431, 468, 529, 626, 657, 664, 702, 828, 829, 923]"
48,22,23.77,"[65, 102, 177, 211, 217, 219, 226, 248, 256, 310, 312, 359, 390, 466, 543, 570, 587, 591, 785, 859, 879, 934]"
49,17,24.94,"[29, 254, 337, 380, 443, 445, 498, 544, 564, 608, 660, 684, 701, 758, 820, 876, 926]"
50,19,24.96,"[384, 92, 113, 192, 251, 278, 446, 654, 683, 708, 749, 801, 824, 826, 865, 871, 955, 968, 985]"
51,19,26.28,"[74, 95, 253, 316, 354, 396, 403, 456, 508, 607, 703, 710, 711, 765, 775, 892, 898, 954, 1000]"
52,22,27.21,"[15, 22, 42, 51, 116, 181, 185, 240, 351, 356, 478, 495, 526, 540, 612, 669, 692, 756, 847, 916, 959, 993]"
53,16,27.74,"[21, 88, 227, 347, 371, 465, 611, 648, 661, 670, 682, 739, 818, 883, 919, 964]"
54,15,29.37,"[28, 31, 126, 120, 124, 195, 216, 239, 246, 485, 563, 578, 637, 676, 844]"
55,9,29.93,"[150, 389, 476, 522, 572, 705, 841, 880, 912]"
56,12,31.21,"[8, 77, 117, 156, 426, 518, 653, 694, 780, 781, 814, 843]"
57,18,33.29,"[133, 45, 75, 127, 179, 183, 212, 263, 267, 340, 486, 506, 515, 659, 713, 911, 938, 946]"
58,15,35.67,"[46, 84, 171, 174, 210, 214, 346, 392, 405, 411, 767, 804, 860, 881, 903]"
59,18,38.41,"[98, 2, 131, 159, 172, 229, 271, 386, 451, 580, 597, 695, 734, 805, 853, 861, 950, 980]"
60,23,41.62,"[32, 86, 141, 279, 313, 324, 455, 500, 568, 588, 614, 719, 755, 768, 776, 798, 856, 884, 893, 908, 933, 971, 995]"
61,10,45.40,"[167, 421, 632, 633, 685, 777, 867, 905, 941, 979]"
62,17,49.95,"[182, 203, 260, 272, 307, 409, 501, 551, 565, 627, 639, 662, 686, 845, 846, 888, 915]"